# Generated by Django 6.1 on 2026-08-18 09:28

import django.db.models.deletion
import pgvector.django.vector
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_topic_chunk'),
        ('exams', '0006_question_edited_at_question_instructor_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=200)),
                ('stem', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('true_false', 'True / false'), ('short_answer', 'Short answer'), ('numeric', 'Numeric problem')], max_length=16)),
                ('level', models.CharField(choices=[('direct', 'Direct recall'), ('medium', 'Applied'), ('multi_step', 'Multi-step')], max_length=12)),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('mark_sum_ok', models.BooleanField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=300)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('from_ocr', models.BooleanField(default=False)),
                ('origin_exam_title', models.CharField(blank=True, max_length=200)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='courses.course')),
                ('origin_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_questions', to='exams.exam')),
                ('origin_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_as', to='exams.question')),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='courses.chunk')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='courses.topic')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BankUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(blank=True, max_length=200)),
                ('is_origin', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bank.bankquestion')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_usages', to='exams.exam')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_usages', to='exams.question')),
            ],
            options={
                'ordering': ['used_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['course', 'question_type', 'level'], name='bank_bankqu_course__e97cd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankusage',
            constraint=models.UniqueConstraint(fields=('bank_question', 'exam'), name='one_usage_per_exam_per_bank_question'),
        ),
    ]
