# Generated by Django 6.1 on 2026-08-14 17:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_topic_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_built', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('true_false', 'True / false'), ('short_answer', 'Short answer'), ('numeric', 'Numeric problem')], default='mcq', max_length=16)),
                ('level', models.CharField(choices=[('direct', 'Direct recall'), ('medium', 'Applied'), ('multi_step', 'Multi-step')], default='medium', max_length=12)),
                ('count', models.PositiveIntegerField(default=1, help_text='Questions to draw from this topic.')),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('weight_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='exams.blueprint')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_rows', to='courses.topic')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('mid', 'Midterm'), ('final', 'Final')], default='mid', max_length=10)),
                ('total_score', models.PositiveIntegerField(default=40, help_text='Marks the exam is out of.')),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=10)),
                ('number_of_forms', models.PositiveIntegerField(default=1, help_text='Equivalent versions of this exam (A, B, …).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blueprint',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='exams.exam'),
        ),
    ]
