# Generated by Django 6.1 on 2026-08-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_topic_chunk'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('true_false', 'True / false'), ('short_answer', 'Short answer'), ('numeric', 'Numeric problem')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('source_ref', models.CharField(help_text='The passage this question cites.', max_length=300)),
                ('from_ocr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='candidate', max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.blueprintrow')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.chunk')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
