# Generated by Django 6.1 on 2026-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='mark_sum_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
