# Generated by Django 6.1 on 2026-08-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_answer_key_question_mark_sum_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=200)),
                ('question_type', models.CharField(blank=True, max_length=16)),
                ('level', models.CharField(blank=True, max_length=12)),
                ('required', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('passed', 'Passed review'), ('needs_attention', 'Needs manual attention')], default='needs_attention', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_runs', to='exams.blueprintrow')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_runs', to='exams.exam')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('passed', 'Passed review'), ('rejected', 'Rejected by review'), ('dropped', 'Dropped before review')], max_length=12)),
                ('stem', models.TextField()),
                ('notes', models.JSONField(blank=True, default=list)),
                ('failed_checks', models.JSONField(blank=True, default=list)),
                ('model_checked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.itemrun')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exams.question')),
            ],
            options={
                'ordering': ['round', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemrun',
            constraint=models.UniqueConstraint(fields=('exam', 'blueprint_row'), name='one_item_run_per_blueprint_row'),
        ),
    ]
