# Generated by Django 6.1 on 2026-08-15 13:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_itemrun_questionattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='form_sharing',
            field=models.CharField(choices=[('separate', 'Fully separate — no question appears on both'), ('shared', 'Sharing allowed — core questions may appear on both')], default='separate', help_text='Whether the forms may share questions.', max_length=12),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=4)),
                ('position', models.PositiveIntegerField(default=0)),
                ('sharing_allowed', models.BooleanField(default=False)),
                ('expected_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='exams.exam')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('expected_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('blueprint_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_entries', to='exams.blueprintrow')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='exams.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_entries', to='exams.question')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('exam', 'label'), name='one_form_per_label_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form', 'question'), name='one_placement_per_question_per_form'),
        ),
    ]
