# Generated by Django 6.1 on 2026-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_form_sharing_form_formquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='instructor_edited',
            field=models.BooleanField(default=False),
        ),
    ]
