# Generated by Django 6.1 on 2026-08-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('exams', '0006_question_edited_at_question_instructor_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='bank_share_percent',
            field=models.PositiveIntegerField(default=50, help_text='Share of the whole exam to draw from the bank, when mixing.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sourcing',
            field=models.CharField(choices=[('new', 'Fully new — write every question from the content'), ('bank', 'From the bank — reuse questions I have already approved'), ('mix', 'A mix — part bank, part newly written')], default='new', help_text="Where this exam's questions come from.", max_length=8),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='bank.bankquestion'),
        ),
    ]
