# Generated by Django 6.1 on 2026-08-12 22:32

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='e.g. CS310', max_length=32)),
                ('level', models.CharField(choices=[('introductory', 'Introductory'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('postgraduate', 'Postgraduate')], default='introductory', max_length=20)),
                ('content_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('mixed', 'Arabic + English')], default='en', help_text='The language of the lecture material, not of the interface.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models.source_file_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('docx', 'Word'), ('txt', 'Plain text')], max_length=10)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Not extracted yet'), ('ready', 'Text extracted'), ('no_text', 'No text layer'), ('unsupported', 'Format not supported yet'), ('failed', 'Extraction failed')], default='pending', max_length=16)),
                ('status_detail', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='1-based page number in the source document.')),
                ('text', models.TextField(blank=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.sourcefile')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('instructor', 'code'), name='unique_course_code_per_instructor'),
        ),
        migrations.AddConstraint(
            model_name='extractedpage',
            constraint=models.UniqueConstraint(fields=('source_file', 'number'), name='unique_page_per_source_file'),
        ),
    ]
