# Generated by Django 6.1 on 2026-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpage',
            name='is_image_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='pages_without_text',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='unmappable_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='status',
            field=models.CharField(choices=[('pending', 'Not extracted yet'), ('ready', 'Text extracted'), ('partial_text', 'Some pages have no text layer'), ('no_text', 'No text layer'), ('unsupported', 'Format not supported yet'), ('failed', 'Extraction failed')], default='pending', max_length=16),
        ),
    ]
