# Generated by Django 6.1 on 2026-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_extractedpage_is_image_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpage',
            name='source',
            field=models.CharField(choices=[('text_layer', 'Text layer'), ('ocr', 'Read by OCR')], default='text_layer', max_length=12),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='ocr_engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='pages_from_ocr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
