# Generated by Django 6.1 on 2026-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_extractedpage_source_sourcefile_ocr_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpage',
            name='ocr_reason',
            field=models.CharField(blank=True, choices=[('image_only', 'No text layer'), ('mixed', 'Text layer covers only part of the page'), ('defective_font', 'Embedded fonts map letters to junk')], default='', max_length=16),
        ),
    ]
