"""The exam and its blueprint: the plan, written down before any question exists.

M4. An `Exam` is the instructor's specification — how long, out of how much, how
many questions, how many forms. A `Blueprint` is how that specification is spent
across the syllabus: one `BlueprintRow` per (topic, question type, level) the
exam will draw on.

Nothing here is generated by a model. The arithmetic that binds these rows to
the exam's totals lives in `exams/services/blueprint.py` and is plain Python —
what can be computed exactly is never handed to an LLM.
"""

from decimal import Decimal

from django.db import models
from django.urls import reverse

from courses.models import Course, Topic


class Exam(models.Model):
    """One exam an instructor is preparing for a course.

    The five numbers on it (`total_score`, `question_count`, `duration_minutes`,
    `number_of_forms`, `language`) are the contract every later milestone is
    checked against: the blueprint must spend exactly this score over exactly
    this many questions, and M10 must produce this many equivalent forms.
    """

    class Kind(models.TextChoices):
        QUIZ = "quiz", "Quiz"
        MIDTERM = "mid", "Midterm"
        FINAL = "final", "Final"

    class Language(models.TextChoices):
        ARABIC = "ar", "Arabic"
        ENGLISH = "en", "English"

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="exams")
    #: Optional — an instructor with three quizzes needs to tell them apart.
    #: Falls back to the kind and creation date in `__str__`.
    title = models.CharField(max_length=200, blank=True)
    kind = models.CharField(max_length=10, choices=Kind.choices, default=Kind.MIDTERM)
    total_score = models.PositiveIntegerField(default=40, help_text="Marks the exam is out of.")
    question_count = models.PositiveIntegerField(default=20)
    duration_minutes = models.PositiveIntegerField(default=60)
    #: The language the questions are written in — not the language of the
    #: material, and not the language of this interface. An Arabic course can
    #: be examined in English.
    language = models.CharField(max_length=10, choices=Language.choices, default=Language.ENGLISH)
    number_of_forms = models.PositiveIntegerField(
        default=1, help_text="Equivalent versions of this exam (A, B, …)."
    )

    class FormSharing(models.TextChoices):
        """How two forms of the same exam are allowed to relate (M9).

        The instructor's call, not إحكام's. Fully separate is the stricter
        paper and the default; sharing is the honest option for a course whose
        core definitions belong on every version of the exam. It is also the
        answer when the pool cannot cover two whole papers — but it is offered
        as a choice, never applied quietly to rescue a thin pool.
        """

        SEPARATE = "separate", "Fully separate — no question appears on both"
        SHARED = "shared", "Sharing allowed — core questions may appear on both"

    #: Meaningless for a one-form exam, which is why the spec screen only shows
    #: it once `number_of_forms` is more than one. Stored regardless, so raising
    #: the form count later does not lose a choice already made.
    form_sharing = models.CharField(
        max_length=12,
        choices=FormSharing.choices,
        default=FormSharing.SEPARATE,
        help_text="Whether the forms may share questions.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.display_title

    def get_absolute_url(self) -> str:
        return reverse("exams:blueprint", args=[self.course_id, self.pk])

    @property
    def display_title(self) -> str:
        return self.title.strip() or f"{self.get_kind_display()} — {self.course.code}"

    @property
    def has_blueprint(self) -> bool:
        return hasattr(self, "blueprint")

    @property
    def form_labels(self) -> list[str]:
        """"A", "B", … — one per form. Used from M9, defined with the count."""
        return [chr(ord("A") + i) for i in range(self.number_of_forms)]

    @property
    def has_multiple_forms(self) -> bool:
        """Whether the sharing question is even askable (M9's conditional reveal)."""
        return self.number_of_forms > 1

    @property
    def forms_may_share(self) -> bool:
        """One form cannot share with itself, whatever the stored setting says."""
        return self.has_multiple_forms and self.form_sharing == self.FormSharing.SHARED

    @property
    def has_forms(self) -> bool:
        return self.forms.exists()


class Blueprint(models.Model):
    """How one exam's score and questions are spread over its topics.

    One per exam: a second blueprint would be a second plan for the same paper,
    and there is no honest way to say which one the questions came from.
    """

    exam = models.OneToOneField(Exam, on_delete=models.CASCADE, related_name="blueprint")
    #: Set when the rows were generated by `auto_build`, cleared the moment the
    #: instructor saves an edit. It is the difference between "إحكام proposed
    #: this" and "the instructor decided this", and the screen says which.
    is_auto_built = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"Blueprint for {self.exam}"

    def get_absolute_url(self) -> str:
        return reverse("exams:blueprint", args=[self.exam.course_id, self.exam_id])


class BlueprintRow(models.Model):
    """One planned block of questions: a topic, a type, a level, a count, a score.

    A topic may appear in several rows — five MCQs and one short answer on the
    same chapter is an ordinary plan — so the validators aggregate by topic
    rather than assuming one row each.
    """

    class QuestionType(models.TextChoices):
        """The MVP types (M5). Diagrams, matching and image-based are deferred."""

        MCQ = "mcq", "Multiple choice"
        TRUE_FALSE = "true_false", "True / false"
        SHORT_ANSWER = "short_answer", "Short answer"
        NUMERIC = "numeric", "Numeric problem"

    class Level(models.TextChoices):
        """Cognitive demand, in the plan's own vocabulary (see M7's level match)."""

        DIRECT = "direct", "Direct recall"
        MEDIUM = "medium", "Applied"
        MULTI_STEP = "multi_step", "Multi-step"

    blueprint = models.ForeignKey(Blueprint, on_delete=models.CASCADE, related_name="rows")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="blueprint_rows")
    question_type = models.CharField(
        max_length=16, choices=QuestionType.choices, default=QuestionType.MCQ
    )
    level = models.CharField(max_length=12, choices=Level.choices, default=Level.MEDIUM)
    count = models.PositiveIntegerField(default=1, help_text="Questions to draw from this topic.")
    #: Marks this row carries in total, not per question. Decimal because half
    #: marks are ordinary in a real paper.
    marks = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal("0"))
    #: Share of the exam this topic is meant to be worth. Stored rather than
    #: derived from `marks` so the two can disagree — which is exactly the
    #: mistake `check_marks_match_weights` exists to catch.
    weight_percent = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0"))
    position = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["position", "pk"]

    def __str__(self) -> str:
        return f"{self.topic.name} · {self.get_question_type_display()} × {self.count}"

    @property
    def marks_per_question(self) -> Decimal:
        """What one question in this row is worth. Zero questions is worth nothing."""
        if not self.count:
            return Decimal("0")
        return (self.marks / self.count).quantize(Decimal("0.01"))


class Question(models.Model):
    """One generated question (M5), and the passage it was written from.

    A row here is *a candidate* until an instructor says otherwise: Agent 2A
    over-generates, Agent 3A (M7) reviews, and the instructor approves or
    rejects. `status` is the only thing that separates a suggestion from a
    question that will be on a paper, so it starts at `CANDIDATE` and is never
    set by a model.

    `source_ref` and `source_chunk` are the citation, kept as both the human
    sentence ("OOP-lecture-3.pdf · page 7") and the link to the chunk it came
    from — the first is what an instructor reads, the second is what lets a
    review screen show the passage beside the question.

    The answer lives on the same row as the stem (`correct`, `explanation`)
    because M6's rule is that the key is produced *with* the question. M6 adds
    the typed key formats on top of these; it never fills them in afterwards.
    """

    class Status(models.TextChoices):
        CANDIDATE = "candidate", "Candidate"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"

    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name="questions")
    #: Nullable so a question outlives the blueprint row it came from — an
    #: instructor re-planning the paper should not silently delete questions
    #: they have already approved.
    blueprint_row = models.ForeignKey(
        BlueprintRow, on_delete=models.SET_NULL, null=True, blank=True, related_name="questions"
    )
    stem = models.TextField()
    question_type = models.CharField(max_length=16, choices=BlueprintRow.QuestionType.choices)
    #: Empty for short answer and numeric; ["True", "False"] for true/false.
    options = models.JSONField(default=list, blank=True)
    correct = models.TextField()
    explanation = models.TextField(blank=True)
    source_ref = models.CharField(max_length=300, help_text="The passage this question cites.")
    source_chunk = models.ForeignKey(
        "courses.Chunk",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="questions",
    )
    #: True when the cited passage is an OCR transcription rather than a text
    #: layer. The question is then quoting a model's reading of a picture, and
    #: review is entitled to know that before approving the wording.
    from_ocr = models.BooleanField(default=False)
    #: The typed answer key (M6), written by the same call that wrote the stem:
    #: a direct key for MCQ and true/false, a model answer plus required
    #: elements for short answer, worked steps with per-step marks plus the final
    #: answer for numeric. JSON rather than columns because the four shapes have
    #: almost nothing in common, and review reads a key whole rather than
    #: querying inside it — see `agents.answer_key.answer_key_from_dict`, which
    #: is how it is read back.
    answer_key = models.JSONField(default=dict, blank=True)
    #: The one thing review *does* query: did a numeric key's per-step marks
    #: total the question's marks? `None` when there was no mark split to add up
    #: (every other type), so "not checked" and "checked and wrong" stay
    #: distinguishable. Set by Python, never by a model, and never auto-fixed.
    mark_sum_ok = models.BooleanField(null=True, blank=True)
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.CANDIDATE)
    position = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["position", "pk"]

    def __str__(self) -> str:
        return self.stem[:80]

    @property
    def is_candidate(self) -> bool:
        return self.status == self.Status.CANDIDATE

    @property
    def key(self):
        """The stored answer key, parsed back into its typed form (M6).

        Stage-3 review reads the stem and this together, in one pass, with no
        model call: the key was written by the same call that wrote the stem.
        """
        from agents.answer_key import answer_key_from_dict  # local: agents imports this module

        return answer_key_from_dict(self.answer_key)

    @property
    def needs_mark_review(self) -> bool:
        """A numeric key whose steps do not total the question's marks."""
        return self.mark_sum_ok is False


class ItemRun(models.Model):
    """What the correction loop did about one blueprint row (M8).

    One row of this per (exam, blueprint row): how many generation rounds it
    took, how many questions came out the other side of review, and whether it
    finished or hit the retry cap and needs an instructor. Re-running an item
    updates this row rather than adding a second one — two records would be two
    answers to "did this row work?".
    """

    class Status(models.TextChoices):
        PASSED = "passed", "Passed review"
        NEEDS_ATTENTION = "needs_attention", "Needs manual attention"

    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name="item_runs")
    #: Nullable for the same reason `Question.blueprint_row` is: the log of what
    #: happened outlives a re-plan.
    blueprint_row = models.ForeignKey(
        BlueprintRow, on_delete=models.SET_NULL, null=True, blank=True, related_name="item_runs"
    )
    #: Copied rather than followed, so the log still reads as a sentence after
    #: the row it describes is gone.
    topic_name = models.CharField(max_length=200, blank=True)
    question_type = models.CharField(max_length=16, blank=True)
    level = models.CharField(max_length=12, blank=True)
    #: What the row asked for, and what review actually passed. Surplus is
    #: normal and kept: `approved_count` may exceed `required`.
    required = models.PositiveIntegerField(default=0)
    approved_count = models.PositiveIntegerField(default=0)
    #: Generation rounds spent: the first batch, plus each gap-fill round.
    rounds = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=16, choices=Status.choices, default=Status.NEEDS_ATTENTION
    )
    #: Set when the loop stopped for a reason that is not "the questions were
    #: bad" — a provider outage, a row with no passages. Distinct from the
    #: rejection notes, which are about questions.
    error = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["pk"]
        constraints = [
            models.UniqueConstraint(
                fields=["exam", "blueprint_row"], name="one_item_run_per_blueprint_row"
            )
        ]

    def __str__(self) -> str:
        return f"{self.topic_name or 'item'} — {self.get_status_display()}"

    @property
    def needs_attention(self) -> bool:
        return self.status == self.Status.NEEDS_ATTENTION

    @property
    def gap_fill_rounds(self) -> int:
        """Rounds spent asking for replacements — the first batch is not one."""
        return max(self.rounds - 1, 0)

    @property
    def shortfall(self) -> int:
        return max(self.required - self.approved_count, 0)

    @property
    def approved_questions(self):
        """The questions of this item that actually passed review.

        The only way into M9's pool. Reading it through the attempts rather than
        through `Question` is deliberate: a question is in the pool because a
        recorded review passed it, not because it exists.
        """
        return Question.objects.filter(
            attempts__item_run=self, attempts__outcome=QuestionAttempt.Outcome.PASSED
        ).distinct()


class QuestionAttempt(models.Model):
    """One candidate the loop produced, and what became of it (M8).

    Every attempt is recorded, not only the survivors: a rejected question and
    the note that rejected it are the audit trail the success metric ("problems
    caught before approval") is counted from, and a candidate dropped for citing
    no supplied passage is why a row came back short. Without these three
    outcomes side by side, a short row is an unexplained gap.

    Nothing here is ever rewritten — an attempt is a fact about a past round.
    """

    class Outcome(models.TextChoices):
        PASSED = "passed", "Passed review"
        REJECTED = "rejected", "Rejected by review"
        #: Never reviewed, because it never became a candidate: its `source_ref`
        #: named no supplied passage, or it came back as the wrong type. M5's
        #: silent drop, made visible.
        DROPPED = "dropped", "Dropped before review"

    item_run = models.ForeignKey(ItemRun, on_delete=models.CASCADE, related_name="attempts")
    #: 1 for the first batch, 2–4 for the gap-fill rounds.
    round = models.PositiveIntegerField(default=1)
    outcome = models.CharField(max_length=12, choices=Outcome.choices)
    stem = models.TextField()
    #: Set only for an attempt that passed and was stored. A rejected or dropped
    #: attempt has no `Question` row by design — storing one would put an
    #: unreviewed question where M9 can reach it.
    question = models.ForeignKey(
        Question, on_delete=models.SET_NULL, null=True, blank=True, related_name="attempts"
    )
    #: Agent 3A's rejection notes, verbatim — the same sentences that were
    #: handed back to Agent 2A as the brief for the replacement.
    notes = models.JSONField(default=list, blank=True)
    failed_checks = models.JSONField(default=list, blank=True)
    #: False when only the deterministic half of review ran. "Passed every
    #: check" and "passed every check we ran" are not the same claim.
    model_checked = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["round", "pk"]

    def __str__(self) -> str:
        return f"round {self.round} · {self.get_outcome_display()} · {self.stem[:60]}"

    @property
    def note(self) -> str:
        return "\n".join(self.notes or [])


class Form(models.Model):
    """One assembled version of the exam — Form A, Form B (M9).

    A form is a *selection*, not a copy: it points at questions in the reviewed
    pool rather than duplicating them, so an instructor's edit to a question in
    M11 reaches every form carrying it instead of drifting apart from itself.
    Which questions those are is decided in `exams/services/forms.py` by plain
    arithmetic over the blueprint — no model is involved in building a paper.

    A `Form` row exists only for a *complete* assembly. `save_assembly` refuses
    to write one that is short of questions, so a form on this table is a paper
    that can be sat; a shortfall is reported on the screen and stays there.

    `expected_minutes` and `total_marks` are stored as assembled rather than
    recomputed on read, because they are what the instructor saw and agreed to.
    """

    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name="forms")
    #: "A", "B" — the label as it is printed on the paper.
    label = models.CharField(max_length=4)
    position = models.PositiveIntegerField(default=0)
    #: What the exam's sharing setting was when this form was built. Copied
    #: rather than followed, so a form still describes how it was made after the
    #: setting is changed.
    sharing_allowed = models.BooleanField(default=False)
    #: A planning estimate summed over the questions — never a claim about how
    #: long students will take. M10 keeps the same naming rule.
    expected_minutes = models.DecimalField(max_digits=7, decimal_places=2, default=Decimal("0"))
    total_marks = models.DecimalField(max_digits=7, decimal_places=2, default=Decimal("0"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["position", "pk"]
        constraints = [
            models.UniqueConstraint(fields=["exam", "label"], name="one_form_per_label_per_exam")
        ]

    def __str__(self) -> str:
        return f"Form {self.label} — {self.exam}"

    @property
    def question_count(self) -> int:
        return self.entries.count()

    @property
    def questions(self):
        """The questions on this paper, in the order they are printed."""
        return Question.objects.filter(form_entries__form=self).order_by(
            "form_entries__position"
        )


class FormQuestion(models.Model):
    """One question's place on one form.

    A through table rather than a many-to-many field because the *placement*
    carries information the question does not: where it sits on this paper, and
    what it is worth here. It is also what makes sharing expressible at all —
    the same question on Form A and Form B is two placements of one question,
    which is exactly what the instructor chose when they allowed sharing.
    """

    form = models.ForeignKey(Form, on_delete=models.CASCADE, related_name="entries")
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="form_entries"
    )
    #: Nullable for the same reason it is on `Question`: a re-plan must not
    #: silently delete an assembled paper.
    blueprint_row = models.ForeignKey(
        BlueprintRow, on_delete=models.SET_NULL, null=True, blank=True, related_name="form_entries"
    )
    position = models.PositiveIntegerField(default=0)
    #: The per-question estimate this placement contributed, and the marks the
    #: blueprint row prices it at. Stored so a form's totals can be read back
    #: without re-deriving them from a row that may since have changed.
    expected_minutes = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal("0"))
    marks = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal("0"))

    class Meta:
        ordering = ["position", "pk"]
        constraints = [
            models.UniqueConstraint(
                fields=["form", "question"], name="one_placement_per_question_per_form"
            )
        ]

    def __str__(self) -> str:
        return f"{self.form.label}{self.position + 1}. {self.question.stem[:60]}"
