"""The exam and its blueprint: the plan, written down before any question exists.

M4. An `Exam` is the instructor's specification — how long, out of how much, how
many questions, how many forms. A `Blueprint` is how that specification is spent
across the syllabus: one `BlueprintRow` per (topic, question type, level) the
exam will draw on.

Nothing here is generated by a model. The arithmetic that binds these rows to
the exam's totals lives in `exams/services/blueprint.py` and is plain Python —
what can be computed exactly is never handed to an LLM.
"""

from decimal import Decimal

from django.db import models
from django.urls import reverse

from courses.models import Course, Topic


class Exam(models.Model):
    """One exam an instructor is preparing for a course.

    The five numbers on it (`total_score`, `question_count`, `duration_minutes`,
    `number_of_forms`, `language`) are the contract every later milestone is
    checked against: the blueprint must spend exactly this score over exactly
    this many questions, and M10 must produce this many equivalent forms.
    """

    class Kind(models.TextChoices):
        QUIZ = "quiz", "Quiz"
        MIDTERM = "mid", "Midterm"
        FINAL = "final", "Final"

    class Language(models.TextChoices):
        ARABIC = "ar", "Arabic"
        ENGLISH = "en", "English"

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="exams")
    #: Optional — an instructor with three quizzes needs to tell them apart.
    #: Falls back to the kind and creation date in `__str__`.
    title = models.CharField(max_length=200, blank=True)
    kind = models.CharField(max_length=10, choices=Kind.choices, default=Kind.MIDTERM)
    total_score = models.PositiveIntegerField(default=40, help_text="Marks the exam is out of.")
    question_count = models.PositiveIntegerField(default=20)
    duration_minutes = models.PositiveIntegerField(default=60)
    #: The language the questions are written in — not the language of the
    #: material, and not the language of this interface. An Arabic course can
    #: be examined in English.
    language = models.CharField(max_length=10, choices=Language.choices, default=Language.ENGLISH)
    number_of_forms = models.PositiveIntegerField(
        default=1, help_text="Equivalent versions of this exam (A, B, …)."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.display_title

    def get_absolute_url(self) -> str:
        return reverse("exams:blueprint", args=[self.course_id, self.pk])

    @property
    def display_title(self) -> str:
        return self.title.strip() or f"{self.get_kind_display()} — {self.course.code}"

    @property
    def has_blueprint(self) -> bool:
        return hasattr(self, "blueprint")

    @property
    def form_labels(self) -> list[str]:
        """"A", "B", … — one per form. Used from M10, defined with the count."""
        return [chr(ord("A") + i) for i in range(self.number_of_forms)]


class Blueprint(models.Model):
    """How one exam's score and questions are spread over its topics.

    One per exam: a second blueprint would be a second plan for the same paper,
    and there is no honest way to say which one the questions came from.
    """

    exam = models.OneToOneField(Exam, on_delete=models.CASCADE, related_name="blueprint")
    #: Set when the rows were generated by `auto_build`, cleared the moment the
    #: instructor saves an edit. It is the difference between "إحكام proposed
    #: this" and "the instructor decided this", and the screen says which.
    is_auto_built = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"Blueprint for {self.exam}"

    def get_absolute_url(self) -> str:
        return reverse("exams:blueprint", args=[self.exam.course_id, self.exam_id])


class BlueprintRow(models.Model):
    """One planned block of questions: a topic, a type, a level, a count, a score.

    A topic may appear in several rows — five MCQs and one short answer on the
    same chapter is an ordinary plan — so the validators aggregate by topic
    rather than assuming one row each.
    """

    class QuestionType(models.TextChoices):
        """The MVP types (M5). Diagrams, matching and image-based are deferred."""

        MCQ = "mcq", "Multiple choice"
        TRUE_FALSE = "true_false", "True / false"
        SHORT_ANSWER = "short_answer", "Short answer"
        NUMERIC = "numeric", "Numeric problem"

    class Level(models.TextChoices):
        """Cognitive demand, in the plan's own vocabulary (see M7's level match)."""

        DIRECT = "direct", "Direct recall"
        MEDIUM = "medium", "Applied"
        MULTI_STEP = "multi_step", "Multi-step"

    blueprint = models.ForeignKey(Blueprint, on_delete=models.CASCADE, related_name="rows")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="blueprint_rows")
    question_type = models.CharField(
        max_length=16, choices=QuestionType.choices, default=QuestionType.MCQ
    )
    level = models.CharField(max_length=12, choices=Level.choices, default=Level.MEDIUM)
    count = models.PositiveIntegerField(default=1, help_text="Questions to draw from this topic.")
    #: Marks this row carries in total, not per question. Decimal because half
    #: marks are ordinary in a real paper.
    marks = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal("0"))
    #: Share of the exam this topic is meant to be worth. Stored rather than
    #: derived from `marks` so the two can disagree — which is exactly the
    #: mistake `check_marks_match_weights` exists to catch.
    weight_percent = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0"))
    position = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["position", "pk"]

    def __str__(self) -> str:
        return f"{self.topic.name} · {self.get_question_type_display()} × {self.count}"

    @property
    def marks_per_question(self) -> Decimal:
        """What one question in this row is worth. Zero questions is worth nothing."""
        if not self.count:
            return Decimal("0")
        return (self.marks / self.count).quantize(Decimal("0.01"))


class Question(models.Model):
    """One generated question (M5), and the passage it was written from.

    A row here is *a candidate* until an instructor says otherwise: Agent 2A
    over-generates, Agent 3A (M7) reviews, and the instructor approves or
    rejects. `status` is the only thing that separates a suggestion from a
    question that will be on a paper, so it starts at `CANDIDATE` and is never
    set by a model.

    `source_ref` and `source_chunk` are the citation, kept as both the human
    sentence ("OOP-lecture-3.pdf · page 7") and the link to the chunk it came
    from — the first is what an instructor reads, the second is what lets a
    review screen show the passage beside the question.

    The answer lives on the same row as the stem (`correct`, `explanation`)
    because M6's rule is that the key is produced *with* the question. M6 adds
    the typed key formats on top of these; it never fills them in afterwards.
    """

    class Status(models.TextChoices):
        CANDIDATE = "candidate", "Candidate"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"

    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name="questions")
    #: Nullable so a question outlives the blueprint row it came from — an
    #: instructor re-planning the paper should not silently delete questions
    #: they have already approved.
    blueprint_row = models.ForeignKey(
        BlueprintRow, on_delete=models.SET_NULL, null=True, blank=True, related_name="questions"
    )
    stem = models.TextField()
    question_type = models.CharField(max_length=16, choices=BlueprintRow.QuestionType.choices)
    #: Empty for short answer and numeric; ["True", "False"] for true/false.
    options = models.JSONField(default=list, blank=True)
    correct = models.TextField()
    explanation = models.TextField(blank=True)
    source_ref = models.CharField(max_length=300, help_text="The passage this question cites.")
    source_chunk = models.ForeignKey(
        "courses.Chunk",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="questions",
    )
    #: True when the cited passage is an OCR transcription rather than a text
    #: layer. The question is then quoting a model's reading of a picture, and
    #: review is entitled to know that before approving the wording.
    from_ocr = models.BooleanField(default=False)
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.CANDIDATE)
    position = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["position", "pk"]

    def __str__(self) -> str:
        return self.stem[:80]

    @property
    def is_candidate(self) -> bool:
        return self.status == self.Status.CANDIDATE
